:ems:
  :ems_autosde:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
        :power:
          :critical:
            - AUTOSDE_instance_power_on
            - AUTOSDE_instance_power_off
:http_proxy:
  :autosde:
    :host:
    :password:
    :port:
    :user:
:ems_refresh:
  :autosde:
    :refresh_interval: 15.minutes
:workers:
  :ems_refresh_worker_autosde:
    :inherits_from: ems_refresh_worker
